---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present

- name: Install Debian OS packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - mesos={{mesos_version}}-1.0.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}

- name: Install Docker
  apt: pkg=docker.io state=present update_cache=yes
  when: docker_support == "yes"

- name: Mesos default config file
  template: src=mesos.j2 dest=/etc/default/mesos
