---
- name: Remove default mesos config file
  file: path={{item}} state=absent
  with_items:
     - /etc/default/mesos
     - /etc/default/mesos-master
     - /etc/default/mesos-slave

- name: Overwrite Zookeeper file
  template: src=zk.j2 dest=/etc/mesos/zk

- name: Restart mesos-master
  service: name=mesos-master state=restarted enabled=yes sleep=5
  when: ansible_os_family == "Debian" and (mesos_install_mode == "master" or mesos_install_mode == "master-slave")

- name: Restart mesos-slave
  service: name=mesos-slave state=restarted enabled=yes sleep=5
  when: ansible_os_family == "Debian" and (mesos_install_mode == "slave" or mesos_install_mode == "master-slave")
