---
- include: slave.yml
- include: master.yml

- name: Remove slave init script override
  file: path=/etc/init/mesos-slave.override state=absent

- name: Remove master init script override
  file: path=/etc/init/mesos-master.override state=absent

- name: Enable mesos-master service on boot
  service: name=mesos-master enabled=yes

- name: Enable mesos-slave service on boot
  service: name=mesos-slave enabled=yes
