---
- name: Disable mesos-slave auto init for master only install
  template: src=mesos-slave.override.j2 dest=/etc/init/mesos-slave.override

- name: Set master --quorum
  template: src=quorum.j2 dest=/etc/mesos-master/quorum
  when: quorum != ""

- name: Set master --cluster name
  template: src=cluster.j2 dest=/etc/mesos-master/cluster
  when: cluster != ""

- name: Set master --quorum
  template: src=quorum.j2 dest=/etc/mesos-master/quorum
  when: quorum != ""

- name: Remove master --log_dir
  file: path=/etc/mesos-master/log_dir state=absent
  when: log_dir == ""

- name: Set master --log_dir
  template: src=log_dir.j2 dest=/etc/mesos-master/log_dir
  when: log_dir != ""

- name: Remove master --ip
  file: path=/etc/mesos-master/ip state=absent
  when: ip == ""

- name: Set master --ip
  template: src=ip.j2 dest=/etc/mesos-master/ip
  when: ip != ""

- name: Remove master --hostname
  file: path=/etc/mesos-master/hostname state=absent
  when: hostname == ""

- name: Set master --hostname
  template: src=hostname.j2 dest=/etc/mesos-master/hostname
  when: hostname != ""

- name: Stop mesos-slave for master install
  service: name=mesos-slave state=stopped enabled=no