---
- include: slave.yml
- include: master.yml

- name: Remove master and slave init script override
  file: path={{item}} state=absent
  with_items:
    - /etc/init/mesos-slave.override
    - /etc/init/mesos-master.override

- name: Enable mesos-master service on boot
  service: name=mesos-master enabled=yes

- name: Enable mesos-slave service on boot
  service: name=mesos-slave enabled=yes
