---
- name: Disable mesos-master auto init for slave only install
  template: src=mesos-master.override.j2 dest=/etc/init/mesos-master.override

- name: Set required --master
  template: src=master.j2 dest=/etc/mesos-slave/master
  when: master != ""

- name: Remove slave --ip
  file: path=/etc/mesos-slave/ip state=absent
  when: ip == ""

- name: Set slave --ip
  template: src=ip.j2 dest=/etc/mesos-slave/ip
  when: ip != ""

- name: Remove slave --hostname
  file: path=/etc/mesos-slave/hostname state=absent
  when: hostname == ""

- name: Set slave --hostname
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname
  when: hostname != ""

- name: Remove slave --checkpoint
  file: path=/etc/mesos-slave/?checkpoint state=absent
  when: checkpoint == ""

- name: Set slave --checkpoint
  file: path=/etc/mesos-slave/?checkpoint state=touch
  when: checkpoint != ""

- name: Remove slave --containerizers
  file: path=/etc/mesos-slave/containerizers state=absent
  when: containerizers == ""

- name: Set slave --containerizers
  template: src=containerizers.j2 dest=/etc/mesos-slave/containerizers
  when: containerizers != ""

- name: Stop mesos-master for slave install
  service: name=mesos-master state=stopped enabled=no
